# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyzetool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog

import calculateParameters as Cp
from PyQt5.QtCore import Qt
import generateMap as Gm


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(471, 720)
        Dialog.setStyleSheet("background-color: rgb(255, 242, 229);")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        Dialog.setWindowFlags(Qt.WindowStaysOnTopHint)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-20, 660, 341, 32))
        self.buttonBox.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 451, 630))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(208, 208, 208);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 420, 411, 141))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_7.setEnabled(True)
        self.checkBox_7.setGeometry(QtCore.QRect(210, 100, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setAcceptDrops(False)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(210, 10, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(210, 70, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_6.setEnabled(True)
        self.checkBox_6.setGeometry(QtCore.QRect(210, 40, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setAcceptDrops(False)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(230, 100, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(230, 40, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(20, 200, 411, 211))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(210, 150, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_5.setEnabled(True)
        self.checkBox_5.setGeometry(QtCore.QRect(210, 180, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setAcceptDrops(False)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 180, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(210, 40, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setAcceptDrops(False)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(210, 10, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 40, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(210, 80, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_2.setGeometry(QtCore.QRect(210, 110, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.timeEdit = QtWidgets.QTimeEdit(self.frame_3)
        self.timeEdit.setGeometry(QtCore.QRect(230, 110, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(20, 60, 411, 131))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setGeometry(QtCore.QRect(210, 60, 171, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 100, 171, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit.setGeometry(QtCore.QRect(210, 20, 171, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(160, 30, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(20, 420, 411, 91))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon_2 = QtGui.QIcon()
        icon_2.addPixmap(QtGui.QPixmap("import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5, clicked = lambda : self.saveEvent())
        self.pushButton_2.setGeometry(QtCore.QRect(140, 20, 50, 50))
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5, clicked = lambda : self.importEvent())
        self.pushButton_3.setGeometry(QtCore.QRect(220, 20, 50, 50))
        self.pushButton_3.setIcon(icon_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(100, 20, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(100, 50, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.spinBox = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox.setGeometry(QtCore.QRect(270, 50, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox.setObjectName("spinBox")
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_11.setGeometry(QtCore.QRect(270, 20, 81, 20))
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.pushButton = QtWidgets.QPushButton(self.frame, clicked = lambda: self.clickedNext())
        self.pushButton.setGeometry(QtCore.QRect(30, 550, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(140, 530, 291, 71))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.listWidget = QtWidgets.QListWidget(self.frame_6)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 291, 71))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.questionFinish)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.rejected.connect(self.cancelDialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.checkBox_11.setDisabled(True)
        self.spinBox.setDisabled(True)
        self.checkBox.setDisabled(True)
        self.checkBox_2.setDisabled(True)
        self.checkBox_5.setDisabled(True)
        self.checkBox_6.setDisabled(True)
        self.lineEdit_2.setDisabled(True)
        self.lineEdit_5.setDisabled(True)
        self.timeEdit.setDisabled(True)
        self.checkBox_7.setDisabled(True)
        self.lineEdit_6.setDisabled(True)
        self.lineEdit_7.setDisabled(True)
        self.pushButton.setDisabled(True)
        self.checkBox_6.hide()
        self.checkBox_7.hide()
        self.lineEdit_6.hide()
        self.lineEdit_7.hide()
        self.label_10.hide()
        self.label_11.hide()
        self.label_7.hide()
        self.frame_2.hide()
        self.label_22.hide()
        self.label_23.hide()
        self.checkBox_11.hide()
        self.spinBox.hide()


        self.checkBox.stateChanged.connect(self.clickedBox)
        self.checkBox_2.stateChanged.connect(self.clickedBox_2)
        self.checkBox_5.stateChanged.connect(self.clickedBox_5)
        self.checkBox_6.stateChanged.connect(self.clickedBox_6)
        self.checkBox_7.stateChanged.connect(self.clickedBox_7)

        self.comboBox.activated[str].connect(self.onSelected_1)

        temp_a = [" "]
        temp_b = [" "]
        for a in Cp.name_launch:
            temp_a.append(a)
        for b in Cp.name_impact:
            temp_b.append(b)
        self.comboBox.addItems(temp_a)
        self.comboBox_2.addItems(temp_b)

    def cancelDialog(self):
        Cp.event_array.clear()

    def okDialog(self):
        Cp.calculate()

    def questionFinish(self):
        msg = QMessageBox()
        msg.setWindowFlags(Qt.WindowStaysOnTopHint)
        msg.setIcon(QMessageBox.Question)
        msg.setText("Do you want to finalize the events ?")
        msg.setWindowTitle("Question")
        msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        msg.accepted.connect(self.okDialog)
        retval = msg.exec_()

    def clickedBox(self, state):
        if state == QtCore.Qt.Checked:
            self.lineEdit_2.setEnabled(True)
            self.checkBox_2.setDisabled(True)
        else:
            self.lineEdit_2.setDisabled(True)
            self.checkBox_2.setEnabled(True)

    def clickedBox_2(self, state):
        if state == QtCore.Qt.Checked:
            self.timeEdit.setEnabled(True)
            self.checkBox.setDisabled(True)
        else:
            self.timeEdit.setDisabled(True)
            self.checkBox.setEnabled(True)

    def clickedBox_5(self, state):
        if state == QtCore.Qt.Checked:
            self.lineEdit_5.setEnabled(True)
            self.checkBox_6.setDisabled(True)
            self.checkBox_7.setDisabled(True)
        else:
            self.lineEdit_5.setDisabled(True)
            #self.checkBox_6.setEnabled(True)
            #self.checkBox_7.setEnabled(True)

    def clickedBox_6(self, state):
        if state == QtCore.Qt.Checked:
            self.lineEdit_6.setEnabled(True)
            self.checkBox_7.setDisabled(True)
            self.checkBox_5.setDisabled(True)
        else:
            #self.lineEdit_6.setDisabled(True)
            #self.checkBox_7.setEnabled(True)
            self.checkBox_5.setEnabled(True)

    def clickedBox_7(self, state):
        if state == QtCore.Qt.Checked:
            self.lineEdit_7.setEnabled(True)
            self.checkBox_6.setDisabled(True)
            self.checkBox_5.setDisabled(True)
        else:
            self.lineEdit_7.setDisabled(True)
            #self.checkBox_6.setEnabled(True)
            self.checkBox_5.setEnabled(True)

    def clickedNext(self):
        a = []
        a.append(self.comboBox.currentText())
        a.append(Cp.actual_launch_coord[Cp.name_launch.index(self.comboBox.currentText())])
        a.append(self.comboBox_2.currentText())
        a.append(Cp.actual_impact_coord[Cp.name_impact.index(self.comboBox_2.currentText())])
        if self.checkBox.isChecked() == True:
            a.append(1)
            a.append(self.lineEdit_2.text())
            if self.checkBox_5.isChecked() == True:
                a.append(1)
                a.append(self.lineEdit_5.text())
            elif self.checkBox_6.isChecked() == True:
                a.append(2)
                a.append(self.lineEdit_6.text())
            elif self.checkBox_7.isChecked() == True:
                a.append(3)
                a.append(self.lineEdit_7.text())
        elif self.checkBox_2.isChecked() == True:
            a.append(2)
            a.append(self.timeEdit.text())
            if self.checkBox_5.isChecked() == True:
                a.append(1)
                a.append(self.lineEdit_5.text())
            elif self.checkBox_6.isChecked() == True:
                a.append(2)
                a.append(self.lineEdit_6.text())
            elif self.checkBox_7.isChecked() == True:
                a.append(3)
                a.append(self.lineEdit_7.text())
        a.append(self.lineEdit.text())
        Cp.event_array.append(a)
        self.lineEdit_2.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.listWidget.clear()
        for i in Cp.event_array:
            self.listWidget.addItem(str(Cp.event_array.index(i) + 1)+ ')   ' + str(i))

    def onSelected_1(self, val):
        if len(Cp.event_array) == 0:
            self.checkBox.setEnabled(True)
            self.checkBox_2.setEnabled(True)
            self.checkBox_5.setEnabled(True)
            #self.checkBox_6.setEnabled(True)
            #self.checkBox_7.setEnabled(True)
            self.pushButton.setEnabled(True)
        else:
            pass

    def saveEvent(self):
        file_filter = 'Text File (*.txt)'
        response = QFileDialog.getSaveFileName(
            parent=None,
            caption='Select a data file',
            directory='mission.txt',
            filter=file_filter,
            initialFilter='Text File (*.txt)'
        )

        file1 = open(response[0], "w")
        for i in Cp.event_array:
            for j in i:
                file1.writelines(str(j) + '\n')
        file1.close()

    def importEvent(self):
        file_filter = 'Text File (*.txt)'
        response = QFileDialog.getOpenFileName(
            parent=None,
            caption='Select a data file',
            directory=os.getcwd(),
            filter=file_filter,
            initialFilter='Text File (*.txt)'
        )
        a=[]
        b=[]
        c=[]
        d=[]
        try:
            with open(response[0]) as f:
                lines = f.read().splitlines()

            for line,i in zip(lines,range(0,len(lines))):
                if i % 9 == 1 or i % 9 == 3:
                    line = line.replace('[','')
                    line = line.replace(']','')
                    b = line.split(', ')
                    for j in b:
                        a.append(float(j))
                    c.append(a)
                    a = []
                    b = []

                elif i % 9 == 4 or i % 9 == 6:
                    c.append(int(line))
                elif i % 9 == 0:
                    c=[]
                    c.append(line)
                else:
                    c.append(line)
                d.append(c)
            for i in d:
                if i not in Cp.event_array:
                    Cp.event_array.append(i)


        except FileNotFoundError:
            pass
        for i in Cp.event_array:
            self.listWidget.addItem(str(Cp.event_array.index(i) + 1)+ ')   ' + str(i))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Event Creation Dialog"))
        self.label_7.setText(_translate("Dialog", "Impact Parameters"))
        self.label_10.setText(_translate("Dialog", "Muzzle Velocity (m/s)"))
        self.label_11.setText(_translate("Dialog", "Average Flight Velocity (m/s)"))
        self.label_6.setText(_translate("Dialog", "Time Past After First Shooting (s)"))
        self.label_5.setText(_translate("Dialog", "Add Time Stamp to the Event (s)"))
        self.label_3.setText(_translate("Dialog", "Firing Event Time Parameters (hh:mm:ss)"))
        self.label_9.setText(_translate("Dialog", "Time of Flight of Caliber (s)"))
        self.timeEdit.setDisplayFormat(_translate("Dialog", "hh:mm:ss"))
        self.label_2.setText(_translate("Dialog", "Select Firing Point"))
        self.label_4.setText(_translate("Dialog", "Select Impact Point"))
        self.label.setText(_translate("Dialog", "Average Speed of Sound (m/s)"))
        self.lineEdit.setText(_translate("Dialog", "330"))
        self.label_21.setText(_translate("Dialog", "SELECT EVENT FEATURES"))
        self.label_22.setText(_translate("Dialog", "Include Vegetation Analysis"))
        self.label_23.setText(_translate("Dialog", "Iteration Radius (meters)"))
        self.pushButton.setText(_translate("Dialog", "ADD EVENT +"))


def showAnalyzeTool():
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    Dialog.exec_()
