# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'discarddialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
import calculateParameters as Cp
import inputDialog as Id
import generateMap as Gm

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(172, 277)
        Dialog.setStyleSheet("background-color: rgb(89, 89, 89);")
        self.pushButton = QtWidgets.QPushButton(Dialog, clicked = lambda: self.discardAction())
        self.pushButton.setGeometry(QtCore.QRect(40, 230, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(200, 200, 191);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog, clicked = lambda: self.discardAction_2())
        self.pushButton_4.setGeometry(QtCore.QRect(40, 230, 93, 28))
        self.pushButton_4.setStyleSheet("background-color: rgb(200, 200, 191);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.hide()
        self.pushButton_5 = QtWidgets.QPushButton(Dialog, clicked = lambda: self.discardAction_3())
        self.pushButton_5.setGeometry(QtCore.QRect(40, 230, 93, 28))
        self.pushButton_5.setStyleSheet("background-color: rgb(200, 200, 191);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.hide()
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 151, 171))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget.setLineWidth(2)
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 10, 151, 171))
        self.listWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.listWidget_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget_2.setLineWidth(2)
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_3 = QtWidgets.QListWidget(Dialog)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 10, 151, 171))
        self.listWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.listWidget_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget_3.setLineWidth(2)
        self.listWidget_3.setObjectName("listWidget_3")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog, clicked=lambda: self.changeList_R())
        self.pushButton_2.setGeometry(QtCore.QRect(90, 190, 41, 28))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rightarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog,clicked=lambda: self.changeList_L())
        self.pushButton_3.setGeometry(QtCore.QRect(40, 190, 41, 28))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("leftarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setDisabled(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.listWidget.addItems(Cp.name_sensor)
        self.listWidget.currentRowChanged.connect(self.listAction)
        self.listWidget_2.addItems(Cp.name_launch)
        self.listWidget_2.currentRowChanged.connect(self.listAction_2)
        self.listWidget_3.addItems(Cp.name_impact)
        self.listWidget_3.currentRowChanged.connect(self.listAction_3)
        self.listWidget_2.hide()
        self.listWidget_3.hide()

        self.const = 3
    def changeList_R(self):
        if self.const==2:
            self.listWidget_2.hide()
            self.pushButton_4.hide()
            self.listWidget_3.hide()
            self.pushButton_5.hide()
            self.listWidget.show()
            self.pushButton.show()
            self.const=3
        elif self.const==3:
            self.listWidget.hide()
            self.pushButton.hide()
            self.listWidget_2.hide()
            self.pushButton_4.hide()
            self.listWidget_3.show()
            self.pushButton_5.show()
            self.const=1
        elif self.const==1:
            self.listWidget.hide()
            self.pushButton.hide()
            self.listWidget_3.hide()
            self.pushButton_5.hide()
            self.listWidget_2.show()
            self.pushButton_4.show()
            self.const=2
        self.pushButton_3.setEnabled(True)

    def changeList_L(self):
        if self.const==2:
            self.listWidget_2.hide()
            self.pushButton_4.hide()
            self.listWidget_3.hide()
            self.pushButton_5.hide()
            self.listWidget.show()
            self.pushButton.show()
            self.const=1
        elif self.const==3:
            self.listWidget.hide()
            self.pushButton.hide()
            self.listWidget_2.hide()
            self.pushButton_4.hide()
            self.listWidget_3.show()
            self.pushButton_5.show()
            self.const=2
        elif self.const==1:
            self.listWidget.hide()
            self.pushButton.hide()
            self.listWidget_3.hide()
            self.pushButton_5.hide()
            self.listWidget_2.show()
            self.pushButton_4.show()
            self.const=3

    def listAction(self,row):
        global val1
        val1 = row

    def discardAction(self):
        global val1
        sensor = val1
        Cp.actual_sensor_coord.pop(sensor)
        Cp.name_sensor.pop(sensor)
        Gm.last_list.pop(-1)
        self.listWidget.takeItem(sensor)

    def listAction_2(self,row):
        global val2
        val2 = row

    def discardAction_2(self):
        global val2
        launch = val2
        Cp.actual_launch_coord.pop(launch)
        Cp.name_launch.pop(launch)
        Gm.last_list.pop(-1)
        self.listWidget_2.takeItem(launch)

    def listAction_3(self,row):
        global val3
        val3 = row

    def discardAction_3(self):
        global val3
        impact = val3
        try:
            Cp.actual_impact_coord.pop(impact)
            Cp.name_impact.pop(impact)
            Gm.last_list.pop(-1)
            self.listWidget_3.takeItem(impact)
        except IndexError:
            pass

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Discard Element"))
        self.pushButton.setText(_translate("Dialog", "Discard"))
        self.pushButton_4.setText(_translate("Dialog", "Discard"))
        self.pushButton_5.setText(_translate("Dialog", "Discard"))


def showDiscardTool():
    Dialog3 = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog3)
    Dialog3.show()
    Dialog3.exec_()

