# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nameElement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import calculateParameters as Cp


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(240, 162)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(25, 110, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 70, 201, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 151, 26))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.accepted.connect(self.getNameSensor)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.setDisabled(True)
        self.lineEdit.textChanged.connect(self.lineActive)

    def lineActive(self, text):
        if len(text) >= 1:
            self.buttonBox.setEnabled(True)
        else:
            self.buttonBox.setDisabled(True)

    def getNameSensor(self):
        Cp.name_sensor.append(self.lineEdit.text())

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sensor Name"))
        self.label.setText(_translate("Dialog", "Please assign name to \n the sensor post"))


def showNameDialog():
    Dialog4 = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog4)
    Dialog4.show()
    Dialog4.exec_()
